Added a keyboardInteractive prop for navigating slides with arrow keys.
kristenmills/torque-react pull request #2
Opened 2016-10-03 18:18 UTC by 7imbrook

See issue #1 

No way to add customization of keys, thats another feature.

2016-10-03 20:54 UTC, kristenmills requested changes

2016-10-03 20:54 UTC, kristenmills commented on src/torque-slides.jsx
> +          countdown: this.props.duration
I think this needs to take into account the possibility of the next slide having a custom duration.  Look at the updateSlide function.

2016-10-03 20:54 UTC, kristenmills commented on src/torque-slides.jsx
> +          countdown: this.props.duration
This one too

2016-10-03 21:01 UTC, kristenmills commented on src/torque-slides.jsx
> +          countdown: this.props.duration
Also the onVisible callback. You might want to pull out a lot of the logic of update slide into a separate function and then call it in keydown and update slide.

2016-10-04 16:02 UTC, 7imbrook commented
My though behind not doing that (other then complexity) was when you navigate the slides the default would be used, so it will stay longer on a slide when your jumping around. I know that the short slides are only ever used for the black/white slides on the GTV but... you now have a flow that can keep you on a slide longer.

Thoughts?

2016-10-04 17:11 UTC, kristenmills commented
You need to at least call on visible. That's how we pull new events and cycle through them for the single event slide. And if you actually want to do an actual keyboard mode, turn off setInterval and the countdown completely and only use the keyboard to control it.

2016-10-05 14:18 UTC, 7imbrook commented
@kristenmills review pls

2016-10-05 17:04 UTC, kristenmills approved these changes

2016-10-05 17:04 UTC, merged